### ISSUE TITLE
an error when  catkin_make

### ISSUE THREAD

**Issue by llzll1031** [pal-robotics/aruco_ros#127]
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
aruco_ros/aruco_msgs/CMakeFiles/aruco_msgs_generate_messages_cpp.dir/build.make:68: recipe for target '/home/lzl/catkin_hand_eye/devel/include/aruco_msgs/Marker.h' failed
why,can you help me?

**Comment by saikishor** [comment]
Hello,

Can you please try with `catkin build`  in a clean workspace?. and try installing it's dependency `sudo apt install python-catkin-tools` to be able to have the catkin build tool.

Thank you,

Best Regards,
PAL Robotics Team

**Comment by llzll1031** [comment]
hello,
 File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
.....
Failed     << aruco_msgs:make                      [ Exited with code 2 ]      
Failed    <<< aruco_msgs                           [ 8.6 seconds ]             
Abandoned <<< aruco_ros                            [ Unrelated job failed ]    
Finished  <<< aruco                                [ 12.5 seconds ]            
[build] Summary: 2 of 4 packages succeeded.        
when I try catkin build in a clean workspace, it failed, also the same mistakes.
hoping  your reply.
Dalian university of technology(China), Robot team

**Comment by saikishor** [comment]
Hello!

We have tried building it on our end and it works. I recommend you to try in a clean docker to test the same or you can install the binary version that is released in the ROS releases. You can install via command line  `sudo apt install ros-melodic-aruco-ros`.

Thank you,

Best Regards,
PAL Robotics Team
